version: '3'

services:
    php:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        environment:
            APP_ENV: dev
            DATABASE_URL: mysql://root:root@mysql:3306/irontec-backend?serverVersion=5.7
        volumes:
            - ./symfony/:/var/www/symfony/
        networks:
            - symfony
        depends_on:
            - mysql
    mysql:
        image: mysql
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        volumes:
            - ./docker/mysql/storage:/var/lib/mysql
        networks:
            - symfony
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        volumes:
            - ./symfony/:/var/www/symfony/
        ports:
            - 8080:80
        networks:
            - symfony
networks:
    symfony:
